"""empty message

Revision ID: 41efc1ab6699
Revises: 7caea66a1dca
Create Date: 2020-05-31 01:11:43.034630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41efc1ab6699'
down_revision = '7caea66a1dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activitytable_title', table_name='activitytable')
    op.create_index(op.f('ix_activitytable_title'), 'activitytable', ['title'], unique=True)
    op.add_column('user_activities', sa.Column('id', sa.Integer(), nullable=True))
    op.drop_constraint('user_activities_user_id_fkey', 'user_activities', type_='foreignkey')
    op.create_foreign_key(None, 'user_activities', 'usertable', ['id'], ['id'])
    op.drop_column('user_activities', 'user_id')
    op.add_column('usertable', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('usertable', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('usertable', 'id')
    op.add_column('user_activities', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_activities', type_='foreignkey')
    op.create_foreign_key('user_activities_user_id_fkey', 'user_activities', 'usertable', ['user_id'], ['user_id'])
    op.drop_column('user_activities', 'id')
    op.drop_index(op.f('ix_activitytable_title'), table_name='activitytable')
    op.create_index('ix_activitytable_title', 'activitytable', ['title'], unique=False)
    # ### end Alembic commands ###
