"""empty message

Revision ID: 47225e14a33a
Revises: 1780b53d426b
Create Date: 2020-05-03 01:45:33.462668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47225e14a33a'
down_revision = '1780b53d426b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitytable',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('learning', sa.String(length=200), nullable=True),
    sa.Column('application', sa.String(length=200), nullable=True),
    sa.Column('support', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activitytable_application'), 'activitytable', ['application'], unique=False)
    op.create_index(op.f('ix_activitytable_description'), 'activitytable', ['description'], unique=False)
    op.create_index(op.f('ix_activitytable_end_date'), 'activitytable', ['end_date'], unique=False)
    op.create_index(op.f('ix_activitytable_learning'), 'activitytable', ['learning'], unique=False)
    op.create_index(op.f('ix_activitytable_reason'), 'activitytable', ['reason'], unique=False)
    op.create_index(op.f('ix_activitytable_start_date'), 'activitytable', ['start_date'], unique=False)
    op.create_index(op.f('ix_activitytable_support'), 'activitytable', ['support'], unique=False)
    op.create_index(op.f('ix_activitytable_title'), 'activitytable', ['title'], unique=False)
    op.create_table('usertable',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('is_cpdChamp', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_usertable_email'), 'usertable', ['email'], unique=True)
    op.create_index(op.f('ix_usertable_first_name'), 'usertable', ['first_name'], unique=False)
    op.create_index(op.f('ix_usertable_last_name'), 'usertable', ['last_name'], unique=False)
    op.create_index(op.f('ix_usertable_role'), 'usertable', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usertable_role'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_last_name'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_first_name'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_email'), table_name='usertable')
    op.drop_table('usertable')
    op.drop_index(op.f('ix_activitytable_title'), table_name='activitytable')
    op.drop_index(op.f('ix_activitytable_support'), table_name='activitytable')
    op.drop_index(op.f('ix_activitytable_start_date'), table_name='activitytable')
    op.drop_index(op.f('ix_activitytable_reason'), table_name='activitytable')
    op.drop_index(op.f('ix_activitytable_learning'), table_name='activitytable')
    op.drop_index(op.f('ix_activitytable_end_date'), table_name='activitytable')
    op.drop_index(op.f('ix_activitytable_description'), table_name='activitytable')
    op.drop_index(op.f('ix_activitytable_application'), table_name='activitytable')
    op.drop_table('activitytable')
    # ### end Alembic commands ###
