"""empty message

Revision ID: 4c8643ce377a
Revises: 9fa0a9416cd6
Create Date: 2020-05-31 01:26:43.179127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8643ce377a'
down_revision = '9fa0a9416cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activitytable_title', table_name='activitytable')
    op.create_index(op.f('ix_activitytable_title'), 'activitytable', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activitytable_title'), table_name='activitytable')
    op.create_index('ix_activitytable_title', 'activitytable', ['title'], unique=False)
    # ### end Alembic commands ###
