"""empty message

Revision ID: 6a59d98d585e
Revises: db66a90a66a4
Create Date: 2020-04-20 02:07:30.788596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a59d98d585e'
down_revision = 'db66a90a66a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usertable_email'), 'usertable', ['email'], unique=True)
    op.create_index(op.f('ix_usertable_first_name'), 'usertable', ['first_name'], unique=False)
    op.create_index(op.f('ix_usertable_last_name'), 'usertable', ['last_name'], unique=False)
    op.create_index(op.f('ix_usertable_role'), 'usertable', ['role'], unique=False)
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_manager', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('project_id', name='projects_pkey')
    )
    op.drop_index(op.f('ix_usertable_role'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_last_name'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_first_name'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_email'), table_name='usertable')
    op.drop_table('usertable')
    # ### end Alembic commands ###
