"""empty message

Revision ID: 7caea66a1dca
Revises: 47225e14a33a
Create Date: 2020-05-03 01:47:11.438304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caea66a1dca'
down_revision = '47225e14a33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activitytable.activity_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usertable.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activities')
    # ### end Alembic commands ###
