"""empty message

Revision ID: db66a90a66a4
Revises: 
Create Date: 2020-04-20 01:42:16.313403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db66a90a66a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.add_column('usertable', sa.Column('first_name', sa.String(length=60), nullable=True))
    op.add_column('usertable', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('usertable', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('usertable', sa.Column('last_name', sa.String(length=60), nullable=True))
    op.add_column('usertable', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.alter_column('usertable', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usertable', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_usertable_email'), 'usertable', ['email'], unique=True)
    op.create_index(op.f('ix_usertable_first_name'), 'usertable', ['first_name'], unique=False)
    op.create_index(op.f('ix_usertable_last_name'), 'usertable', ['last_name'], unique=False)
    op.create_index(op.f('ix_usertable_role'), 'usertable', ['role'], unique=False)
    op.drop_column('usertable', 'surname')
    op.drop_column('usertable', 'password')
    op.drop_column('usertable', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('usertable', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('usertable', sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_usertable_role'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_last_name'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_first_name'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_email'), table_name='usertable')
    op.alter_column('usertable', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('usertable', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('usertable', 'password_hash')
    op.drop_column('usertable', 'last_name')
    op.drop_column('usertable', 'is_admin')
    op.drop_column('usertable', 'id')
    op.drop_column('usertable', 'first_name')
    op.create_table('projects',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_manager', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('project_id', name='projects_pkey')
    )
    # ### end Alembic commands ###
